print("seiyvanet tqveni 5 ojaxis wevris saxeli da asaki")
a= input("seiyvanet tqveni pirveli ojaxis wevris saxeli da asaki: ")
b= input("seiyvanet tqveni meore ojaxis wevris saxeli da asaki: ")
c= input("seiyvanet tqveni mesame ojaxis wevris saxeli da asaki: ")
d= input("seiyvanet tqveni meotxe ojaxis wevris saxeli da asaki: ")
e= input("seiyvanet tqveni mexute ojaxis wevris saxeli da asaki: ")
print("tqveni pirveli ojaxis wevris saxeli da asaki aris: ", a)
print("tqveni meore ojaxis wevris saxeli da asaki aris: ", b)
print("tqveni mesame ojaxis wevris saxeli da asaki aris: ", c)
print("tqveni meotxe ojaxis wevris saxeli da asaki aris: ", d)
print("tqveni mexute ojaxis wevris saxeli da asaki aris: ", e)